# Generated by Django 6.0.7 on 2026-07-09 16:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('craft_fee_rate', models.DecimalField(decimal_places=2, default=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('master_fee_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('owner_fee_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('material_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('craft_fee_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('master_fee_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('owner_fee_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FurnitureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.furniture')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
