# Generated by Django 6.0.7 on 2026-07-09 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='craft_fee_amount',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='craft_fee_rate',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='master_fee_amount',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='master_fee_rate',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='material_total',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='owner_fee_amount',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='owner_fee_rate',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='furnituredetail',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
