# Generated by Django 6.0.7 on 2026-07-09 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_furniture_craft_fee_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituredetail',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
