# Generated by Django 6.0.7 on 2026-07-09 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_furnituredetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='craft_fee_amount',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='master_fee_amount',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='material_total',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='owner_fee_amount',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='furnituredetail',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
