# Generated by Django 6.0.7 on 2026-07-10 21:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_detail_alter_furnituredetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituredetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
