# Generated by Django 6.0.7 on 2026-07-19 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_furnituredetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituredetail',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture_items', to='app.detail'),
        ),
    ]
