# Generated by Django 6.0.6 on 2026-07-31 10:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_resync_furniture_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klinetlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqt'), ('credit', 'Nasiya')], max_length=10, verbose_name="To'lov turi")),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Jami summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="To'langan summa")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan vaqt')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app.client', verbose_name='Klient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shgan")),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Summa')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="To'lov vaqti")),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mebel nomi (saqlangan)')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Soni')),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Sotish narxi')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Summa')),
                ('furniture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.furniture', verbose_name='Mebel')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Sotuv mahsuloti',
                'verbose_name_plural': 'Sotuv mahsulotlari',
                'ordering': ['id'],
            },
        ),
    ]
