# Generated by Django 6.0.6 on 2026-08-21 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_furniture_quantity_sale_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Zahiradagi soni'),
        ),
    ]
